services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\UserRepository: ~

    App\Service\AuthService:
        arguments:
            $doctrine: '@doctrine'
            $passwordHasher: '@security.password_hasher'
            $userRepository: '@App\Repository\UserRepository'
            
    App\Service\OrgService:
        arguments:
            $doctrine: '@doctrine'

    # Add more service definitions when explicit configuration is needed
    # Please note that last definitions always *replace* previous ones
